name: Test with Docker Image

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  test_with_docker:
    runs-on: ubuntu-latest
    container:
      image: jackb001/ci_image-dev:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Black
        id: run_black
        run: |
          black --check .
        continue-on-error: true

      - name: Run Pylint
        id: run_pylint
        run: |
          pylint *.py
        continue-on-error: true

      - name: Run Flake8
        id: run_flake8
        run: |
          flake8 .
        continue-on-error: true

      - name: Evaluate Results
        run: |
          if [ "${{ steps.run_black.outcome }}" != "success" ]; then
            echo "Black failed"
            exit 1
          fi

          if [ "${{ steps.run_pylint.outcome }}" != "success" ]; then
            echo "Pylint failed"
            exit 1
          fi

          if [ "${{ steps.run_flake8.outcome }}" != "success" ]; then
            echo "Flake8 failed"
            exit 1
          fi

          
